hsp = 0;
vsp = 0;
grv = 0.2;
done = 0;
ScreenShake(6,60);
image_speed = 0;
image_index = 0;
game_set_speed(30,gamespeed_fps);
with (oCamera) follow = other.id;
audio_stop_all();
audio_play_sound(snPDeath,19,false);